[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  included_files = ["data/users.json"]

[[redirects]]
  from = "/api/login"
  to = "/.netlify/functions/login"
  status = 200

[[redirects]]
  from = "/api/logout"
  to = "/.netlify/functions/logout"
  status = 200

[[redirects]]
  from = "/api/me"
  to = "/.netlify/functions/me"
  status = 200

[[redirects]]
  from = "/api/config"
  to = "/.netlify/functions/get-config"
  status = 200

[[redirects]]
  from = "/api/config/save"
  to = "/.netlify/functions/save-config"
  status = 200

[[redirects]]
  from = "/api/logs"
  to = "/.netlify/functions/get-logs"
  status = 200

[[redirects]]
  from = "/api/users"
  to = "/.netlify/functions/get-users"
  status = 200

[[redirects]]
  from = "/api/users/reset-password"
  to = "/.netlify/functions/reset-user-password"
  status = 200

[[redirects]]
  from = "/api/change-password"
  to = "/.netlify/functions/change-password"
  status = 200

[[redirects]]
  from = "/api/users/add"
  to = "/.netlify/functions/add-user"
  status = 200

[[redirects]]
  from = "/api/users/delete"
  to = "/.netlify/functions/delete-user"
  status = 200

[[redirects]]
  from = "/api/users/update-permissions"
  to = "/.netlify/functions/update-user-permissions"
  status = 200
[[redirects]]
  from = "/api/block-ips"
  to = "/.netlify/functions/get-block-ips"
  status = 200

[[redirects]]
  from = "/api/log-block-ip"
  to = "/.netlify/functions/log-block-ip"
  status = 200

[[redirects]]
  from = "/api/block-ips/unblock"
  to = "/.netlify/functions/unblock-block-ip"
  status = 200

  [[redirects]]
  from = "/api/public/domains52b"
  to = "/.netlify/functions/public-domains52b"
  status = 200

  [[redirects]]
  from = "/api/public/domains1b"
  to = "/.netlify/functions/public-domains1b"
  status = 200

  [[redirects]]
  from = "/api/public/domains0b"
  to = "/.netlify/functions/public-domains0b"
  status = 200

   [[redirects]]
  from = "/api/public/domains789"
  to = "/.netlify/functions/public-domains789"
  status = 200

[[edge_functions]]
  path = "/"
  function = "ip-guard"

[[edge_functions]]
  path = "/index.html"
  function = "ip-guard"
